### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pacmancoder** [true-grue/ayumi#1]
Hello! I [forked](https://github.com/pacmancoder/ayumi-lib) your project for using it in my ZX Spectrum [emulator](https://github.com/pacmancoder/rustzx) - I made bare library repository, which can be used as static/dynamic library (I plan to write micro Makefiles in future) so I can write Rust bindings for it. But I can't find your project's license. So, what type of license is using by your project? Can I distribute your lib as a part of my open-source project?

**Comment by true-grue** [comment]
Hi Vladislav!

I've added MIT license to the repo. Feel free to use Ayumi and good luck
with your emulator!
I will be glad to anwer any questions.

2016-07-09 22:29 GMT+03:00 Vladislav Nikonov notifications@github.com:

> Hello! I forked https://github.com/pacmancoder/ayumi-lib your project
> for using it in my ZX Spectrum emulator
> https://github.com/pacmancoder/rustzx - I made bare library repository,
> which can be used as static/dynamic library (I plan to write Makefiles in
> future) but I can't find your project's license. So, can I assign MIT
> license with your name to it?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/true-grue/ayumi/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AD46BN_O3Mm-A5siVzH3zeO65ump1Lubks5qT_avgaJpZM4JIr1z
> .

## 

Regards,
Peter Sovietov

**Comment by pacmancoder** [comment]
Thank you!
