### ISSUE TITLE
Usage permission

### ISSUE THREAD

**Issue by Markets00** [true-grue/ayumi#2]
Hi! I've developed this [Z80 asm AY-3-8910 player](https://github.com/Markets00/TFG),  so, I'm working on a crossplatform Tracker to generate songs to that player. Can I use your library to generate the AY sounds at the tracker?

Also, may you upload some code usage? The simplest example will be helpful.
Thanks.

**Comment by true-grue** [comment]
Hi! Sure, feel free to use it in your project. You may find some examples of usage of the library here:
1. https://github.com/true-grue/ayumi/blob/master/ayumi_render.c
2. https://github.com/alexanderk23/ayumi-js/blob/master/index.html

**Comment by Markets00** [comment]
Thank you! Probably, I will write you again when I publish the software.
