### ISSUE TITLE
supported formats

### ISSUE THREAD

**Issue by wothke** [true-grue/ayumi#3]
Hi 

This is not an issue but rather a question: 

I just came across the JavaScript version of your player and I found that it plays some .fym format that I haven't encountered before (see my various web players: http://www.wothke.ch/tinyrsid/index.php/webaudio-players). Actually that seems to be the only file format that is supported by the JavaScript version of your player. From what I see it is some zlib compressed file and guessing from the variable name it supposedly is some kind of "PSG dump".. but apparently nor the .fym nor the content ".psg" file is something that other players like ZXtune know how to handle...

Are these any "standard" file formats (and if so could you point me to some docs? and where can respective music files be found?) or are those formats specific to your player?

Cheers.

**Comment by true-grue** [comment]
Hi!

There is a Flash YM player and I was asked to support its format a long time ago. You may hear the player in action here: http://ym.mmcm.ru/flash.php
Here are some sources: http://zx-pk.ru/threads/9251-aym-player-na-flash-10-mechty-sbyvayutsya-)/page11.html
And here is my code for reading FYM format: https://github.com/true-grue/ayumi/blob/master/fym_to_text.py

Hope it helps!

**Comment by wothke** [comment]
Thanks for the feedback :-) So if I get this correctly your player is actually using Vortex Tracker II .TXT files as input and you have Python converter scripts for AFX, FYM, PSG and YM format files?  But the guy that did the JavaScript version so far only implemented the FYM loader?

PS: I don't know what the original hardware would have sounded like.. but the 1st song (see "Misfire by Scalesmann^march[ing]_cats" on http://ym.mmcm.ru/) sounds kind of weird (WebAudio player) about 24 secs into the song.. sounds a bit like an overamplify issue to me..

Cheers.

**Comment by true-grue** [comment]
Correct, Alexander Kovalenko implemented only FYM support in his version of the player.

In fact, it's my own TXT format for internal use in the player :) Basically, it all is just a demo for Ayumi engine. The main planned use for Ayumi was VSTi plugin, but its sources are not opened yet.

Sorry, there is nothing I can say about the issues with the other players/versions.

**Comment by wothke** [comment]
I decided to do little Web port of my own - with the "complete" set of loaders: http://www.wothke.ch/webAyumi/ 
(What is the .afx format and where can I find respective files for testing?)

**Comment by true-grue** [comment]
See AYFX Editor here: https://shiru.untergrund.net/software.shtml

**Comment by true-grue** [comment]
Just saw your page -- really impressive! In fact, I was totally surprised that JS versions of Ayumi could work so flawlessly. I was thinking that my C code, especially, the resampler part, is too heavy for it.

**Comment by joric** [comment]
Made simple ayumi text dump to fym converter, [text_to_fym.py](https://pastebin.com/gDWSCU4n)
